/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AiDiagnosis {
  'treatmentAdvice' : string,
  'diagnosis' : string,
  'symptoms' : string,
  'cropType' : string,
  'confidence' : bigint,
  'preventionTips' : string,
}
export interface Buyer {
  'id' : BuyerId,
  'cropsBought' : Array<string>,
  'name' : string,
  'company' : string,
  'contactEmail' : string,
  'location' : string,
  'contactPhone' : string,
}
export type BuyerId = bigint;
export interface ContactMessage {
  'farmerContactEmail' : string,
  'message' : string,
  'buyerId' : BuyerId,
  'timestamp' : Time,
  'farmer' : Principal,
  'farmerName' : string,
}
export interface CropScan {
  'treatmentAdvice' : string,
  'diagnosis' : string,
  'timestamp' : Time,
  'cropType' : string,
  'image' : ExternalBlob,
  'farmer' : Principal,
}
export interface DashboardData {
  'farmerProfile' : [] | [FarmerProfile],
  'messageCount' : bigint,
  'recentScans' : Array<CropScan>,
}
export type ExternalBlob = Uint8Array;
export interface FarmerProfile {
  'farmName' : string,
  'name' : string,
  'crops' : Array<string>,
  'contactEmail' : string,
  'location' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Add a new buyer (admin only)
   */
  'addBuyer' : ActorMethod<
    [string, string, string, Array<string>, string, string],
    undefined
  >,
  /**
   * / Analyze symptoms and return a diagnosis (simulated)
   */
  'analyzeSymptoms' : ActorMethod<[string, string], AiDiagnosis>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'fetchExternalData' : ActorMethod<[string], string>,
  /**
   * / Get all crop scans (admin only)
   */
  'getAllCropScans' : ActorMethod<[], Array<CropScan>>,
  /**
   * / Get all farmer profiles (admin only)
   */
  'getAllFarmerProfiles' : ActorMethod<[], Array<FarmerProfile>>,
  /**
   * / Get all messages (admin only)
   */
  'getAllMessages' : ActorMethod<[], Array<ContactMessage>>,
  /**
   * / Get all buyers (users only)
   */
  'getBuyers' : ActorMethod<[], Array<Buyer>>,
  /**
   * / Get your own farmer profile
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [FarmerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get crop scans for a specific farmer
   */
  'getCropScansForFarmer' : ActorMethod<[Principal], Array<CropScan>>,
  /**
   * / Get recent activity for a farmer (profile, recent scans, message count)
   */
  'getDashboardData' : ActorMethod<[Principal], DashboardData>,
  /**
   * / Get all messages for a specific farmer
   */
  'getMessagesForFarmer' : ActorMethod<[], Array<ContactMessage>>,
  /**
   * / Get another farmer's profile (by owner or admin)
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [FarmerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Save a new crop scan record (requires token and profile)
   */
  'recordCropScan' : ActorMethod<[CropScan], undefined>,
  /**
   * / Register or update a farmer profile (requires user role)
   */
  'saveCallerUserProfile' : ActorMethod<[FarmerProfile], undefined>,
  /**
   * / Send a message to a buyer (requires profile)
   */
  'sendContactMessage' : ActorMethod<[BuyerId, string], undefined>,
  'storeExternalBlob' : ActorMethod<[ExternalBlob], ExternalBlob>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];