/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AiDiagnosis = IDL.Record({
  'treatmentAdvice' : IDL.Text,
  'diagnosis' : IDL.Text,
  'symptoms' : IDL.Text,
  'cropType' : IDL.Text,
  'confidence' : IDL.Nat,
  'preventionTips' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CropScan = IDL.Record({
  'treatmentAdvice' : IDL.Text,
  'diagnosis' : IDL.Text,
  'timestamp' : Time,
  'cropType' : IDL.Text,
  'image' : ExternalBlob,
  'farmer' : IDL.Principal,
});
export const FarmerProfile = IDL.Record({
  'farmName' : IDL.Text,
  'name' : IDL.Text,
  'crops' : IDL.Vec(IDL.Text),
  'contactEmail' : IDL.Text,
  'location' : IDL.Text,
});
export const BuyerId = IDL.Nat;
export const ContactMessage = IDL.Record({
  'farmerContactEmail' : IDL.Text,
  'message' : IDL.Text,
  'buyerId' : BuyerId,
  'timestamp' : Time,
  'farmer' : IDL.Principal,
  'farmerName' : IDL.Text,
});
export const Buyer = IDL.Record({
  'id' : BuyerId,
  'cropsBought' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'company' : IDL.Text,
  'contactEmail' : IDL.Text,
  'location' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const DashboardData = IDL.Record({
  'farmerProfile' : IDL.Opt(FarmerProfile),
  'messageCount' : IDL.Nat,
  'recentScans' : IDL.Vec(CropScan),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBuyer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [],
      [],
    ),
  'analyzeSymptoms' : IDL.Func([IDL.Text, IDL.Text], [AiDiagnosis], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'fetchExternalData' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllCropScans' : IDL.Func([], [IDL.Vec(CropScan)], ['query']),
  'getAllFarmerProfiles' : IDL.Func([], [IDL.Vec(FarmerProfile)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getBuyers' : IDL.Func([], [IDL.Vec(Buyer)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(FarmerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCropScansForFarmer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CropScan)],
      ['query'],
    ),
  'getDashboardData' : IDL.Func([IDL.Principal], [DashboardData], ['query']),
  'getMessagesForFarmer' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(FarmerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordCropScan' : IDL.Func([CropScan], [], []),
  'saveCallerUserProfile' : IDL.Func([FarmerProfile], [], []),
  'sendContactMessage' : IDL.Func([BuyerId, IDL.Text], [], []),
  'storeExternalBlob' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AiDiagnosis = IDL.Record({
    'treatmentAdvice' : IDL.Text,
    'diagnosis' : IDL.Text,
    'symptoms' : IDL.Text,
    'cropType' : IDL.Text,
    'confidence' : IDL.Nat,
    'preventionTips' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CropScan = IDL.Record({
    'treatmentAdvice' : IDL.Text,
    'diagnosis' : IDL.Text,
    'timestamp' : Time,
    'cropType' : IDL.Text,
    'image' : ExternalBlob,
    'farmer' : IDL.Principal,
  });
  const FarmerProfile = IDL.Record({
    'farmName' : IDL.Text,
    'name' : IDL.Text,
    'crops' : IDL.Vec(IDL.Text),
    'contactEmail' : IDL.Text,
    'location' : IDL.Text,
  });
  const BuyerId = IDL.Nat;
  const ContactMessage = IDL.Record({
    'farmerContactEmail' : IDL.Text,
    'message' : IDL.Text,
    'buyerId' : BuyerId,
    'timestamp' : Time,
    'farmer' : IDL.Principal,
    'farmerName' : IDL.Text,
  });
  const Buyer = IDL.Record({
    'id' : BuyerId,
    'cropsBought' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'company' : IDL.Text,
    'contactEmail' : IDL.Text,
    'location' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const DashboardData = IDL.Record({
    'farmerProfile' : IDL.Opt(FarmerProfile),
    'messageCount' : IDL.Nat,
    'recentScans' : IDL.Vec(CropScan),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBuyer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [],
        [],
      ),
    'analyzeSymptoms' : IDL.Func(
        [IDL.Text, IDL.Text],
        [AiDiagnosis],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'fetchExternalData' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllCropScans' : IDL.Func([], [IDL.Vec(CropScan)], ['query']),
    'getAllFarmerProfiles' : IDL.Func([], [IDL.Vec(FarmerProfile)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getBuyers' : IDL.Func([], [IDL.Vec(Buyer)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(FarmerProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCropScansForFarmer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CropScan)],
        ['query'],
      ),
    'getDashboardData' : IDL.Func([IDL.Principal], [DashboardData], ['query']),
    'getMessagesForFarmer' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(FarmerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordCropScan' : IDL.Func([CropScan], [], []),
    'saveCallerUserProfile' : IDL.Func([FarmerProfile], [], []),
    'sendContactMessage' : IDL.Func([BuyerId, IDL.Text], [], []),
    'storeExternalBlob' : IDL.Func([ExternalBlob], [ExternalBlob], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };